### ISSUE TITLE
!!! Märgin siia need asjad, mida tegema peame:

### ISSUE THREAD

**Issue by mihkelvilismae** [mihkelvilismae/tartu-library-app#44]
Final push:
- [x] error handling tööle androidis - #63 Mihkel
- [x] raamatute jne nimekirjade koostamise juures tehha nii, et kui raamat on lisatud, siis kaotab ära nimekirjast - #65  Gert
- [x] loadingscreen disableda pärast alustamist   - #66   Mihkel
- [x] errorteated eesti keelde admin osas - #64 Gert
- [x] sorteerimine  - #67 Gert
- [x] http://admin-mihkelvilismae.rhcloud.com/AdminInterface/json/Zanrid tööle - #68  Gert
- [x] tõlked - #69 Mihkel
- [x]  presentatsioon mõelda
- [x] headeri tekstid muuta - #70 Mihkel
- [x] filtrid tööle ja testida - #71 Mihkel
- [x] aja slider tööle #72

Vähemtähtsad: 
- [x] android välimust parandada (nupud suureks jne)

Android 
- [x]  ilusaks - #40 Mihkel
- [x]  tulemustelehed - #46 Mihkel
- [x]  soovitus -> otsing #58 Mihkel
- [x]  keywordsid php-st
- [x]  kasutajate valiku meeldejätmine - #57 Mihkel
- [x]  greenhouse - #47 Mihkel
- [x]  tekstid üle vaadata
- [x] Php ilusaks
- [x]  keywordside lisamine #56 Gert
- [x]  autocompleteks lõpuks osad väljad
- [x]  loading screen (data võtmiseks) #60 Mihkel

Wiki -  #50 #52 Ainika
- [x]  fn nõuded täiendada
- [x]  deploy lehele lisada ka adminInterface default user ja parool (admin/parool, vist)

Mittefn nõuded - #53 #51  Ainika
- [x]  2 nõuet kokku
- [x]  testimine päris inimestega (küsimustik mõelda)

Admininterface (php) 
- [x]  testid (ntx koormustest: 100 req alla 1 sec; jMeter) #55

Testid
- [x]  Selenium adminInterfacele (mitte recorded, vaid käsitsi teha testid), näiteks mingid kirje lisamise vms testid - #45 Tanel
- [ ]  Androidile espresso

Peer review
- [x] Response - #49 Ainika

**Comment by ainika** [comment]
I assign myself to Wiki and Mittefn nõuded, @mihkelvilismae ask me for help with keywords and search if you need anything

**Comment by mihkelvilismae** [comment]
Tehke kõik endale eraldi issued ka nende asjade kohta, siis saame punkte keskkonna korrektse kasutamise eest :D 

Ma editin siis oma algset postitust ka  ja lisan sinna juurde issuede viited. Kohe teengi seda paari issuega.

**Comment by mihkelvilismae** [comment]
Tehke siis samuti nagu Tanel tegi, et pange esimesse committi kirja nii selle taski number 
(#44) kui ka siis enda taski number, siis saab siit taskist kiiresti ülevaate teistest taskidest.

**Comment by mihkelvilismae** [comment]
Väga hea, lets keep up the good work, team :)

**Comment by mihkelvilismae** [comment]
St preagu ma olen kusjuures väga optimistlikult meelestatud: kui mantra on selline, et "tulemus on tähtsam kui protsess", siis me oleme õnnestunud :D
